# Use postgres/example user/password credentials
version: '3.1'

services:
  database:
    image: mysql:8.0
    container_name: sswm-mysql-container
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD : ssjjmt206
      MYSQL_DATABASE : sswm
      TZ: Asia/Seoul
    ports:
      - 3316:3306
  redis:
    image: redis:latest
    container_name: sswm-redis-container
    restart: always
    ports:
      - 6380:6379
